### ISSUE TITLE
Bedrock - Add support for authenticating using Assume Role instead of AWS Access Keys

### ISSUE THREAD

**Issue by roeisavion** [traceloop/hub#46]
We need to add support for authenticating using Assume Role instead of AWS Access Keys, meaning that the service would get the IAM role from the pod instead of getting the AWS Access Keys from the config.yaml.

I have already created a draft for it with cursor, have not tested it yet.

I guess it can look something like:

src/providers/bedrock/provider.rs:

```
#[cfg(not(test))]
impl ClientProvider for BedrockProvider {
    async fn create_client(&self) -> Result<BedrockRuntimeClient, String> {
        use aws_config::BehaviorVersion;
        use aws_config::Region;
        use aws_credential_types::Credentials;

        let region = self.config.params.get("region").unwrap().clone();
        
        // Check if IAM role-based authentication should be used
        let use_iam_role = self.config.params
            .get("use_iam_role")
            .map(|v| v.parse::<bool>().unwrap_or(false))
            .unwrap_or(false);

        let sdk_config = if use_iam_role {
            // Use default credential provider chain (supports IAM roles, instance profiles, etc.)
            aws_config::defaults(BehaviorVersion::latest())
                .region(Region::new(region))
                .load()
                .await
        } else {
            // Use explicit credentials (existing behavior)
            let access_key_id = self.config.params.get("AWS_ACCESS_KEY_ID")
                .ok_or_else(|| "AWS_ACCESS_KEY_ID is required when use_iam_role is false".to_string())?
                .clone();
            let secret_access_key = self.config.params.get("AWS_SECRET_ACCESS_KEY")
                .ok_or_else(|| "AWS_SECRET_ACCESS_KEY is required when use_iam_role is false".to_string())?
                .clone();
            let session_token = self.config.params.get("AWS_SESSION_TOKEN").cloned();

            let credentials = Credentials::from_keys(access_key_id, secret_access_key, session_token);

            aws_config::defaults(BehaviorVersion::latest())
                .region(Region::new(region))
                .credentials_provider(credentials)
                .load()
                .await
        };

        Ok(BedrockRuntimeClient::new(&sdk_config))
    }
}
```

config-example.yaml:

```
providers:
  # Bedrock configuration with explicit AWS credentials (existing method)
  - key: bedrock
    type: bedrock
    api_key: ""# Not used for AWS Bedrock
    region: "<your-aws-region>" # like "us-east-1"
    inference_profile_id: "<your-inference-profile-id>" # like "us"
    AWS_ACCESS_KEY_ID: "<your-aws-access-key>"
    AWS_SECRET_ACCESS_KEY: "<your-aws-secret-key>"
    AWS_SESSION_TOKEN: "<your-session-token>"  # Optional

  # Bedrock configuration with IAM role-based authentication (recommended for Kubernetes/EKS)
  - key: bedrock-iam
    type: bedrock
    api_key: ""# Not used for AWS Bedrock
    region: "<your-aws-region>" # like "us-east-1"
    inference_profile_id: "<your-inference-profile-id>" # like "us"
    use_iam_role: "true"  # Use IAM roles for service accounts (IRSA) or instance profiles
```
